export const dummy = [
  // Latest
  {
    id: 1,
    type: 'Rent',
    category: 'Latest',
    title: '6 Bedroom Detached Duplex With Rooftop Terrace',
    price: '₦2,700,000.00 ',
    location: 'Abuja, Nigeria',
    image: 'house4.svg',
    beds: 6,
    baths: 2,
    duration: ' Year',
    size: '5x7 m²',
  },
  {
    id: 2,
    type: 'Buy',
    category: 'Latest',
    title: 'Luxury 4 Bedroom Duplex',
    price: '₦120,000,000.00',
    location: 'Lagos, Nigeria',
    image: 'house2.svg',
    beds: 4,
    baths: 3,
    duration: ' Year',
    size: '6x8 m²',
  },
  {
    id: 3,
    type: 'Shortlet',
    category: 'Latest',
    title: 'Modern 3 Bedroom Apartment',
    price: '₦80,000.00 ',
    location: 'Port Harcourt, Nigeria',
    image: 'house3.svg',
    beds: 3,
    baths: 2,
    duration: ' Night',
    size: '4x6 m²',
  },
  {
    id: 4,
    type: 'Rent',
    category: 'Latest',
    title: 'Cozy 2 Bedroom Flat',
    price: '₦900,000.00 ',
    location: 'Ibadan, Nigeria',
    image: 'house1.svg',
    beds: 2,
    baths: 1,
    duration: ' Year',
    size: '3x5 m²',
  },

  // Popular
  {
    id: 5,
    type: 'Rent',
    category: 'Popular',
    title: 'Spacious 5 Bedroom Duplex',
    price: '₦3,500,000.00 ',
    location: 'Enugu, Nigeria',
    image: 'house2.svg',
    beds: 5,
    baths: 3,
    duration: ' Year',
    size: '6x8 m²',
  },
  {
    id: 6,
    type: 'Buy',
    category: 'Popular',
    title: 'Classic 3 Bedroom Bungalow',
    price: '₦45,000,000.00',
    location: 'Kano, Nigeria',
    image: 'house3.svg',
    beds: 3,
    baths: 2,
    duration: ' Year',
    size: '5x7 m²',
  },
  {
    id: 7,
    type: 'Shortlet',
    category: 'Popular',
    title: 'Elegant 2 Bedroom Apartment',
    price: '₦60,000.00 ',
    location: 'Benin, Nigeria',
    image: 'house4.svg',
    beds: 2,
    baths: 2,
    duration: ' Night',
    size: '4x6 m²',
  },
  {
    id: 8,
    type: 'Rent',
    category: 'Popular',
    title: 'Affordable 1 Bedroom Studio',
    price: '₦500,000.00 ',
    location: 'Jos, Nigeria',
    image: 'house1.svg',
    beds: 1,
    baths: 1,
    duration: ' Year',
    size: '3x5 m²',
  },

  // Luxury
  {
    id: 9,
    type: 'Buy',
    category: 'Luxury',
    title: 'Presidential 7 Bedroom Mansion',
    price: '₦250,000,000.00',
    location: 'Banana Island, Lagos',
    image: 'house4.svg',
    beds: 7,
    baths: 8,
    duration: ' Year',
    size: '10x15 m²',
  },
  {
    id: 10,
    type: 'Rent',
    category: 'Luxury',
    title: 'Penthouse 5 Bedroom Apartment',
    price: '₦15,000,000.00 ',
    location: 'Victoria Island, Lagos',
    image: 'house2.svg',
    beds: 5,
    baths: 5,
    duration: ' Year',
    size: '8x12 m²',
  },
  {
    id: 11,
    type: 'Shortlet',
    category: 'Luxury',
    title: 'Executive 4 Bedroom Shortlet',
    price: '₦200,000.00 ',
    location: 'Lekki, Lagos',
    image: 'house3.svg',
    beds: 4,
    baths: 4,
    duration: ' Night',
    size: '7x10 m²',
  },
  {
    id: 12,
    type: 'Buy',
    category: 'Luxury',
    title: 'Luxury 6 Bedroom Duplex',
    price: '₦180,000,000.00',
    location: 'Asokoro, Abuja',
    image: 'house1.svg',
    beds: 6,
    baths: 7,
    duration: ' Year',
    size: '9x13 m²',
  },

  // Affordable
  {
    id: 13,
    type: 'Rent',
    category: 'Affordable',
    title: 'Mini Flat',
    price: '₦350,000.00 ',
    location: 'Oshodi, Lagos',
    image: 'house2.svg',
    beds: 1,
    baths: 1,
    duration: ' Year',
    size: '3x4 m²',
  },
  {
    id: 14,
    type: 'Buy',
    category: 'Affordable',
    title: 'Starter 2 Bedroom Apartment',
    price: '₦8,000,000.00',
    location: 'Abeokuta, Ogun',
    image: 'house3.svg',
    beds: 2,
    baths: 2,
    duration: ' Year',
    size: '4x6 m²',
  },
  {
    id: 15,
    type: 'Shortlet',
    category: 'Affordable',
    title: 'Budget 1 Bedroom Shortlet',
    price: '₦25,000.00 ',
    location: 'Onitsha, Anambra',
    image: 'house4.svg',
    beds: 1,
    baths: 1,
    duration: ' Night',
    size: '3x4 m²',
  },
  {
    id: 16,
    type: 'Rent',
    category: 'Affordable',
    title: 'Affordable 2 Bedroom Flat',
    price: '₦600,000.00 ',
    location: 'Sango, Ogun',
    image: 'house1.svg',
    beds: 2,
    baths: 1,
    duration: ' Year',
    size: '3x5 m²',
  },
  {
    id: 17,
    type: 'Shortlet',
    category: 'Latest',
    title: 'Modern 2 Bedroom Apartment',
    price: '₦15,000,000.00',
    location: 'Abuja, Nigeria',
    image: 'house1.svg',
    beds: 2,
    baths: 2,
    duration: ' N/A',
    size: '4x6 m²',
  },
  {
    id: 18,
    type: 'Shortlet',
    category: 'Popular',
    title: 'Spacious 4 Bedroom Duplex',
    price: '₦65,000,000.00',
    location: 'Lagos, Nigeria',
    image: 'house2.svg',
    beds: 4,
    baths: 3,
    duration: ' N/A',
    size: '6x9 m²',
  },
  {
    id: 19,
    type: 'Shortlet',
    category: 'Luxury',
    title: 'Exclusive 5 Bedroom Mansion',
    price: '₦220,000,000.00',
    location: 'Ikoyi, Lagos',
    image: 'house3.svg',
    beds: 5,
    baths: 6,
    duration: ' N/A',
    size: '9x12 m²',
  },
  {
    id: 20,
    type: 'Shortlet',
    category: 'Affordable',
    title: 'Starter 1 Bedroom Flat',
    price: '₦6,500,000.00',
    location: 'Ibadan, Nigeria',
    image: 'house4.svg',
    beds: 1,
    baths: 1,
    duration: ' N/A',
    size: '3x4 m²',
  },
  {
    id: 21,
    type: 'Shortlet',
    category: 'Latest',
    title: 'Contemporary 3 Bedroom Duplex',
    price: '₦38,000,000.00',
    location: 'Enugu, Nigeria',
    image: 'house2.svg',
    beds: 3,
    baths: 3,
    duration: ' N/A',
    size: '5x8 m²',
  },
  {
    id: 22,
    type: 'Shortlet',
    category: 'Popular',
    title: 'Elegant 2 Bedroom Apartment',
    price: '₦12,000,000.00',
    location: 'Kano, Nigeria',
    image: 'house1.svg',
    beds: 2,
    baths: 2,
    duration: ' N/A',
    size: '4x6 m²',
  },
  {
    id: 23,
    type: 'Shortlet',
    category: 'Luxury',
    title: 'Presidential 6 Bedroom Villa',
    price: '₦300,000,000.00',
    location: 'Banana Island, Lagos',
    image: 'house4.svg',
    beds: 6,
    baths: 7,
    duration: ' N/A',
    size: '12x16 m²',
  },
  {
    id: 24,
    type: 'Shortlet',
    category: 'Affordable',
    title: 'Affordable 2 Bedroom Flat',
    price: '₦10,000,000.00',
    location: 'Oshodi, Lagos',
    image: 'house3.svg',
    beds: 2,
    baths: 1,
    duration: ' N/A',
    size: '3x5 m²',
  },
  {
    id: 25,
    type: 'Buy',
    category: 'Latest',
    title: 'Stylish 1 Bedroom Studio',
    price: '₦8,000,000.00',
    location: 'Port Harcourt, Nigeria',
    image: 'house2.svg',
    beds: 1,
    baths: 1,
    duration: ' N/A',
    size: '3x4 m²',
  },
  {
    id: 26,
    type: 'Buy',
    category: 'Popular',
    title: 'Family 3 Bedroom Bungalow',
    price: '₦28,000,000.00',
    location: 'Jos, Nigeria',
    image: 'house1.svg',
    beds: 3,
    baths: 2,
    duration: ' N/A',
    size: '5x7 m²',
  },
  {
    id: 27,
    type: 'Buy',
    category: 'Luxury',
    title: 'Grand 7 Bedroom Mansion',
    price: '₦270,000,000.00',
    location: 'Asokoro, Abuja',
    image: 'house3.svg',
    beds: 7,
    baths: 8,
    duration: ' N/A',
    size: '10x14 m²',
  },
  {
    id: 28,
    type: 'Buy',
    category: 'Affordable',
    title: 'Compact 2 Bedroom Apartment',
    price: '₦9,500,000.00',
    location: 'Abeokuta, Ogun',
    image: 'house4.svg',
    beds: 2,
    baths: 2,
    duration: ' N/A',
    size: '4x6 m²',
  },
  {
    id: 29,
    type: 'Buy',
    category: 'Latest',
    title: 'Modern 4 Bedroom Duplex',
    price: '₦55,000,000.00',
    location: 'Benin, Nigeria',
    image: 'house2.svg',
    beds: 4,
    baths: 3,
    duration: ' N/A',
    size: '6x9 m²',
  },
  {
    id: 30,
    type: 'Buy',
    category: 'Popular',
    title: 'Stylish 2 Bedroom Apartment',
    price: '₦13,000,000.00',
    location: 'Owerri, Nigeria',
    image: 'house1.svg',
    beds: 2,
    baths: 2,
    duration: ' N/A',
    size: '4x6 m²',
  },
  {
    id: 31,
    type: 'Buy',
    category: 'Luxury',
    title: 'Executive 5 Bedroom Penthouse',
    price: '₦190,000,000.00',
    location: 'Victoria Island, Lagos',
    image: 'house4.svg',
    beds: 5,
    baths: 5,
    duration: ' N/A',
    size: '8x12 m²',
  },
  {
    id: 32,
    type: 'Rent',
    category: 'Affordable',
    title: 'Budget 1 Bedroom Studio',
    price: '₦7,000,000.00',
    location: 'Onitsha, Anambra',
    image: 'house3.svg',
    beds: 1,
    baths: 1,
    duration: ' N/A',
    size: '3x4 m²',
  },
]
